#!/bin/sh

echo "Compiling coffeescript"
if [ -d "src/" ]; then
	rm -fr lib/
	npm install coffee-script
	node_modules/.bin/coffee -b -c -o lib/ src/
	npm uninstall coffee-script
	echo "Compiled coffeescript"
fi